In [1]:
from pathlib import Path
import numpy as np

In [2]:
SEQ = Path.home() / \
"HDD/EventDatasets/EVIMO2_official/left_camera/imo/train/scene13_dyn_test_02_000000"

info = np.load(SEQ / "dataset_info.npz", allow_pickle=True)

print(type(info))

<class 'numpy.lib.npyio.NpzFile'>


In [3]:
print("="*80)
print("Keys")
print("="*80)

for key in info.files:
    print(key)

print()
print("Total keys:", len(info.files))

Keys
index
discretization
K
D
meta

Total keys: 5


In [5]:
for key in info.files:

    x = info[key]

    print("=" * 100)
    print(f"KEY : {key}")
    print("=" * 100)

    print("Type :", type(x))
    print("Shape:", x.shape)
    print("Dtype:", x.dtype)

    # ---------------------------------------------------------
    # Scalar objects (dict, list, etc.)
    # ---------------------------------------------------------
    if x.ndim == 0:

        value = x.item()

        print("\nScalar object")
        print("----------------")
        print("Python type:", type(value))

        if isinstance(value, dict):

            print("\nDictionary contains", len(value), "keys\n")

            for k in value.keys():
                print(" -", k)

        elif isinstance(value, (list, tuple)):

            print("\nLength:", len(value))

            for i, v in enumerate(value[:10]):
                print(i, type(v))

            if len(value) > 10:
                print("...")

        else:

            print(value)

    # ---------------------------------------------------------
    # Arrays
    # ---------------------------------------------------------
    else:

        print("\nArray statistics")
        print("----------------")
        print("Size :", x.size)

        if np.issubdtype(x.dtype, np.number):

            print("Min :", np.min(x))
            print("Max :", np.max(x))

        # ---------- 1D ----------
        if x.ndim == 1:

            print("\nFirst 10 values")
            print(x[:10])

            if len(x) > 10:
                print("Last 10 values")
                print(x[-10:])

        # ---------- 2D ----------
        elif x.ndim == 2:

            print("\nFirst 5 rows")
            print(x[:5])

        # ---------- Higher dimensions ----------
        else:

            print("\nFirst element")
            print(x[0])

    print()

KEY : index
Type : <class 'numpy.ndarray'>
Shape: (1301,)
Dtype: uint32

Array statistics
----------------
Size : 1301
Min : 0
Max : 62915814

First 10 values
[     0  33475  66685  99106 130861 162541 194876 226526 259274 293412]
Last 10 values
[62705303 62732892 62760499 62786650 62811597 62834581 62856578 62878193
 62900541 62915814]

KEY : discretization
Type : <class 'numpy.ndarray'>
Shape: ()
Dtype: float64

Scalar object
----------------
Python type: <class 'float'>
0.01

KEY : K
Type : <class 'numpy.ndarray'>
Shape: (3, 3)
Dtype: float64

Array statistics
----------------
Size : 9
Min : 0.0
Max : 556.573975

First 5 rows
[[556.573975   0.       321.846008]
 [  0.       556.086975 225.617996]
 [  0.         0.         1.      ]]

KEY : D
Type : <class 'numpy.ndarray'>
Shape: (4,)
Dtype: float64

Array statistics
----------------
Size : 4
Min : -0.10828
Max : 0.206233

First 10 values
[-0.10828   0.206233  0.        0.      ]

KEY : meta
Type : <class 'numpy.ndarray'>
Shape: ()
D

In [6]:
meta = info["meta"].item()

print("="*80)
print("META KEYS")
print("="*80)

for k in meta.keys():
    print(k)

META KEYS
frames
full_trajectory
imu
meta


In [7]:
for key, value in meta.items():

    print("="*100)
    print(key)
    print("="*100)

    print("Type :", type(value))

    if isinstance(value, np.ndarray):
        print("Shape :", value.shape)
        print("Dtype :", value.dtype)

        if value.size < 20:
            print(value)
        else:
            print("First entries")
            print(value[:5])

    elif isinstance(value, dict):
        print("Dictionary with", len(value), "keys")

        for k in value.keys():
            print("-", k)

    else:
        print(value)

    print()

frames
Type : <class 'list'>
[{'11': {'pos': {'q': {'w': 0.585027, 'x': -0.335705, 'y': 0.483852, 'z': -0.557613}, 'rpy': {'p': 0.192941, 'r': -1.25332, 'y': -1.662719}, 't': {'x': -0.065853, 'y': -0.176571, 'z': 0.877851}}, 'ts': 0.016667}, '14': {'pos': {'q': {'w': 0.094307, 'x': 0.002985, 'y': 0.869472, 'z': 0.484888}, 'rpy': {'p': 0.161806, 'r': 2.116191, 'y': 3.043509}, 't': {'x': -0.17867, 'y': -0.409818, 'z': 1.370505}}, 'ts': 0.016667}, '15': {'pos': {'q': {'w': -0.43688, 'x': 0.897906, 'y': 0.051071, 'z': 0.017087}, 'rpy': {'p': -0.07538, 'r': -2.238834, 'y': 0.077079}, 't': {'x': -0.316058, 'y': -0.335077, 'z': 1.709033}}, 'ts': 0.016667}, '22': {'pos': {'q': {'w': 0.556665, 'x': 0.576746, 'y': 0.561446, 'z': -0.205588}, 'rpy': {'p': 1.039634, 'r': 2.194195, 'y': 0.973156}, 't': {'x': -0.056635, 'y': -0.25087, 'z': 1.035446}}, 'ts': 0.016667}, '23': {'pos': {'q': {'w': -0.476749, 'x': -0.480856, 'y': 0.625578, 'z': 0.387479}, 'rpy': {'p': -0.225757, 'r': 1.825051, 'y': -1.656

In [8]:
frames = meta["frames"]

print(type(frames))
print("Number of frames :", len(frames))

print("\nFirst frame\n")
print(frames[0])

print("\nLast frame\n")
print(frames[-1])

<class 'list'>
Number of frames : 782

First frame

{'11': {'pos': {'q': {'w': 0.585027, 'x': -0.335705, 'y': 0.483852, 'z': -0.557613}, 'rpy': {'p': 0.192941, 'r': -1.25332, 'y': -1.662719}, 't': {'x': -0.065853, 'y': -0.176571, 'z': 0.877851}}, 'ts': 0.016667}, '14': {'pos': {'q': {'w': 0.094307, 'x': 0.002985, 'y': 0.869472, 'z': 0.484888}, 'rpy': {'p': 0.161806, 'r': 2.116191, 'y': 3.043509}, 't': {'x': -0.17867, 'y': -0.409818, 'z': 1.370505}}, 'ts': 0.016667}, '15': {'pos': {'q': {'w': -0.43688, 'x': 0.897906, 'y': 0.051071, 'z': 0.017087}, 'rpy': {'p': -0.07538, 'r': -2.238834, 'y': 0.077079}, 't': {'x': -0.316058, 'y': -0.335077, 'z': 1.709033}}, 'ts': 0.016667}, '22': {'pos': {'q': {'w': 0.556665, 'x': 0.576746, 'y': 0.561446, 'z': -0.205588}, 'rpy': {'p': 1.039634, 'r': 2.194195, 'y': 0.973156}, 't': {'x': -0.056635, 'y': -0.25087, 'z': 1.035446}}, 'ts': 0.016667}, '23': {'pos': {'q': {'w': -0.476749, 'x': -0.480856, 'y': 0.625578, 'z': 0.387479}, 'rpy': {'p': -0.225757, 'r':

In [11]:
imu = meta["imu"]

print("="*80)
print("IMU TOPICS")
print("="*80)

for topic in imu.keys():
    print(topic)

IMU TOPICS
/prophesee/left/imu
/prophesee/right/imu


In [12]:
topic = list(imu.keys())[0]

print("="*80)
print(topic)
print("="*80)

stream = imu[topic]

print(type(stream))
print("Number of measurements :", len(stream))

print("\nFirst measurement\n")
print(stream[0])

print("\nLast measurement\n")
print(stream[-1])

/prophesee/left/imu
<class 'list'>
Number of measurements : 13354

First measurement

{'angular_velocity': {'x': -0.101333, 'y': 0.016911, 'z': 0.064315}, 'linear_acceleration': {'x': 9.342373, 'y': 0.40895, 'z': -2.726131}, 'ts': 0.017079}

Last measurement

{'angular_velocity': {'x': -0.046206, 'y': 0.049268, 'z': 0.015713}, 'linear_acceleration': {'x': 9.188493, 'y': 1.609453, 'z': 1.24062}, 'ts': 13.025297}


In [13]:
topic = list(imu.keys())[1]

print("="*80)
print(topic)
print("="*80)

stream = imu[topic]

print(type(stream))
print("Number of measurements :", len(stream))

print("\nFirst measurement\n")
print(stream[0])

print("\nLast measurement\n")
print(stream[-1])

/prophesee/right/imu
<class 'list'>
Number of measurements : 13152

First measurement

{'angular_velocity': {'x': 0.068044, 'y': 0.024767, 'z': 0.030893}, 'linear_acceleration': {'x': -9.360934, 'y': 0.026345, 'z': -2.189048}, 'ts': 0.017198}

Last measurement

{'angular_velocity': {'x': -0.000133, 'y': -0.032091, 'z': -0.011452}, 'linear_acceleration': {'x': -9.223819, 'y': -1.236429, 'z': 1.753753}, 'ts': 13.032561}


In [14]:
trajectory = meta["full_trajectory"]

print("="*80)
print("FULL TRAJECTORY")
print("="*80)

print(type(trajectory))
print("Length :", len(trajectory))

print("\nFirst entry\n")
print(trajectory[0])

print("\nLast entry\n")
print(trajectory[-1])

FULL TRAJECTORY
<class 'list'>
Length : 2603

First entry

{'11': {'pos': {'q': {'w': 0.585078, 'x': -0.335862, 'y': 0.483819, 'z': -0.557495}, 'rpy': {'p': 0.192853, 'r': -1.253481, 'y': -1.662382}, 't': {'x': -0.065952, 'y': -0.176197, 'z': 0.87788}}, 'ts': 0.019351}, '14': {'pos': {'q': {'w': 0.094293, 'x': 0.002974, 'y': 0.869553, 'z': 0.484744}, 'rpy': {'p': 0.161807, 'r': 2.116528, 'y': 3.043569}, 't': {'x': -0.178823, 'y': -0.409296, 'z': 1.370593}}, 'ts': 0.019351}, '15': {'pos': {'q': {'w': -0.326337, 'x': 0.57153, 'y': 0.624322, 'z': -0.420809}, 'rpy': {'p': 0.073598, 'r': -2.01975, 'y': 1.705279}, 't': {'x': -0.316649, 'y': -0.334304, 'z': 1.709178}}, 'ts': 0.019351}, '22': {'pos': {'q': {'w': 0.556738, 'x': 0.576728, 'y': 0.561355, 'z': -0.205688}, 'rpy': {'p': 1.039809, 'r': 2.193815, 'y': 0.972661}, 't': {'x': -0.056735, 'y': -0.250453, 'z': 1.035506}}, 'ts': 0.019351}, '23': {'pos': {'q': {'w': -0.476744, 'x': -0.480632, 'y': 0.625744, 'z': 0.387495}, 'rpy': {'p': -0.226

In [15]:
scene_meta = meta["meta"]

print("="*80)
print("SCENE METADATA")
print("="*80)

print(type(scene_meta))

if isinstance(scene_meta, dict):

    print("\nKeys")
    for k in scene_meta.keys():
        print("-", k)

    print("\nContents\n")

    for k, v in scene_meta.items():
        print(f"{k}")
        print(v)
        print()

else:
    print(scene_meta)

SCENE METADATA
<class 'dict'>

Keys
- cx
- cy
- dist_model
- fx
- fy
- k1
- k2
- k3
- k4
- p1
- p2
- res_x
- res_y
- ros_time_offset

Contents

cx
321.846008

cy
225.617996

dist_model
radtan

fx
556.573975

fy
556.086975

k1
-0.10828

k2
0.206233

k3
0.0

k4
0.0

p1
-0.00065

p2
-0.000555

res_x
640

res_y
480

ros_time_offset
1606265562.494869

